/****************************************************************
  recurrence_spatial.h

  Contracting and branching RMEs in SpNCCI basis

  Anna E. McCoy
  Argonne National Lab

  SPDX-License-Identifier: MIT

  08/15/24 (aem): Created.
****************************************************************/

#ifndef SPNCCI_RECURRENCE_BRANCHING_
#define SPNCCI_RECURRENCE_BRANCHING_

// #include "basis/basis.h"
#include "basis/operator.h"
#include "spncci_basis/recurrence_indexing_spatial.h"
// #include "vcs_cache.h"


namespace spncci{

  // For a given omega omega' pair
  // -> Apply recurrence matrix to seeds and branch go generate unit_tensor_rmes
  // -> Create Matrix of relative SU(3) reduced operator rmes with same
  //    x0 appearing in ww' space and spin operators in reuccurence_spin space (S0 T0 ...)
  //    and store in operator_blocks.  Maybe have full set of rmes stored in some hash table
  //    or block structure
  //
  // -> Pass corresponding operator space

  /// Returns a block of branching coefficients for given omega'S'J' and omegaSJ pair.
  /// with rows indexed by L_ket, by kappa_ket, by L_bra by kappa_bra
  /// and cols indexed by omega0, by L0, by kappa0, by rho0
  basis::OperatorBlock<double> GenerateBranchingCoefBlock(
    u3::U3 omega_ket,
    u3::U3 omega_bra,
    auto S_ket,
    auto S_bra,
    auto S0,
    auto J_ket,
    auto J_bra,
    auto J0,
    auto& recurrence_u3_space
    )
  {
    basis::OperatorBlock<double> coef_block;
    return coef_block;

  }

  void BranchRecurrenceSubspace(
    const spatial::RecurrenceU3Space()& recurrence_u3_space,
    const unsigned int upsilon_max_bra,
    const unsigned int upsilon_max_ket,
    const spin::RecurrenceSpinSpace()& recurrence_spin_space,
    const basis::OperatorBlock<double>& unit_tensor_rmes, // omega,omega' x SS' tile
    const basis::OperatorBlocks<double>& operator_blocks, //vector indexed by S0
    const basis::OperatorBlocks<double>& branching_coef_blocks, // vector indexed by S0 of branching coefficient blocks
    const auto& operator_space, //x0 L0 k0 indexing (assumed to have same x0 ordering as in recurrence_u3_space)
    const auto& lanczos_segment_source, //fixed omega,S,gamma[SpSn]. Segment indexed by upsilon,L,kappa
    const auto& lanczos_segment_target //fixed omega',S',gamma',[Sp'Sn']. Segment indexed by upsilon',L',kappa'
    )
  {
    const auto& omega_ket=recurrence_u3_space.omega_ket();
    const auto& omega_bra=recurrence_u3_space.omega_bra();
    const bool branch_to_so3=true;
    u3subspace_ket = sp3r::U3Subspace(
      omega_ket,
      upsilon_max_ket,
      branch_to_so3,{abs(J-S),J+S}
      );

    u3subspace_bra = sp3r::U3Subspace(
      omega_bra,
      upsilon_max_bra,//Replace with dummy?
      branch_to_so3,{abs(J-S),Jp+Sp}
      );
    // Calculate SU(3) coupling coefficients
    // Store in Wcoefs block with w0 L0 k0 rho0 rows and L L' kk' cols
    basis::operatorBlock<double>Wcoefs;

    const auto upsilon_degeneracy = upsilon_max_bra*upsilon_max_ket;
    // matrix accumulating
    int num_S0=3; // For two body recurrence.
    basis::OperatorBlock<double> contracted_rmes = basis::OperatorBlock<double>::Zero(upsilon_degeneracy*Wcoefs.rows(),num_S0);
    for (int spin_operator_index=0; spin_operator_index<recurrence_spin_space.size(); spin_operator_index++)
    {
       const auto& S0 = spin::twobody::OperatorLabelsST::ALLOWED_LABELS[index].S0();
       const auto& T0 = spin::twobody::OperatorLabelsST::ALLOWED_LABELS[index].T0();
       const auto& operator_rmes = operator_blocks[S0].col(spin_operator_index);
       const auto& unit_tenor_rmes.col(spin_operator_index);

       ////Contraction step
       int contraction_index=0;

       for(int x0_index=0; x0_index<recurrence_u3_space.size(); ++x0_index)
        // should be same index for x0 subspace of recurrence_u3_space and operator_space since
        // operator_space subspaces generated by looping over recurrence_u3_space.
        const auto& x0_operator_subspace=operator_space.GetSubspace(x0_index);


        const auto& x0_recurrence_subspace = recurrence_u3_space.GetSubspace(x0_index);
        const auto rho_max = recurrence_u3_space.GetSubspaceDegeneracy(x0_index);
        const auto num_Nbar_pairs = x0_recurrence_subspace.size();
        auto x0_operator_offset = operator_space.GetSubspaceOffset(x0_index);

        for(int L0_index=0; L0_index<x0_subspace.size(); L0_index++)
          // Get k0_max as degeneracy of subspace
          auto k0_max=x0_operator_subspace.GetSubspace(L0_index).degeneracy();
          for(auto k0_index=0; k0_index<k0_max; k0_index++)
            // Get sub array from operator block
            for(auto rho0_index=0; rho0_index<rho0_max; ++rho0_index)
            {
             for(int upsilon_index=0; upsilon_index<upsilon_degeneracy; ++upsilon_index)
              {
                operator_offset = x0_offset+x0_operator_subspace.GetSubspaceOffset(L0_index,k0_index+1);
                const auto& operator_segment = operator_rmes.segment(operator_offset,num_Nbar_pairs);

                //  Get sub array from unit_tensor_rmes
                auto unit_tensor_offset
                      =upsilon_index*recurrence_u3_space.dimension()
                        +recurrence_u3_space.GetSubspaceOffset(x0_index,rho0_index+1);// multiplicity is 1 based.
                const auto& unit_tensor_segment=unit_tensor_rmes.segment(unit_tensor_offset,num_Nbar_pairs);

                contracted_rmes(contraction_index,S0)+=operator_segment.dot(unit_tensor_segment);
                // TODO: If isospin basis contraction step requires additional CG coef for isospin branching.
                 contraction_index++;
               }
        }
    }//end spin index

  //// Branching
  basis::OperatorBlock<double> matrix_elements = basis::OperatorBlock<double>::Zero(branching_coef_blocks[0].rows(),upsilon_degeneracy);
  for(unsigned int S0 : std::vector<unsigned int>{0,1,2})
  {
    const basis::OperatorBlock<double>& branching_coefs = branching_coef_blocks[S0];
    const basis::OperatorBlock<double>& contracted_rme_block = contracted_rmes.col(S0).reshape(branching_coefs.cols(),upsilon_degeneracy);
     matrix_elements += branching_coefs*contracted_rme_block;
  }

// act on lanczos vector segment
for (unsigned int upsilon_ket_index=0; upsilon_ket_index<upsilon_ket_bra; upsilon_ket_index++)
  for (unsigned int upsilon_bra_index=0; upsilon_bra_index<upsilon_max_bra; upsilon_bra_index++)
    {
      // Get offset in source and target vectors/matrices
      int source_offset = upsilon_ket_index*u3_subspace_ket.size();
      int target_offset = upsilon_bra_index*u3_subspace_bra.size();
      basis::OperatorBlock<double>& Lkappa_block = matrix_elements.col(upsilon_ket_index*upsilon_max_bra+upsilon_bra_index);
      lanczos_segment_target.block(source_offset,0,Lkappa_block.rows(),lanczos_segment_source.cols()); += Lkappa_block*lanczos_segment_target.block(source_offset,0,Lkappa_block.cols(),lanczos_segment_source.cols());
    }



  }

}// spncci namespace


#endif
