image: rikorose/gcc-cmake

stages:
  - configure
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

configure:
  stage: configure
  before_script:
    - apt update && apt -y install libgsl-dev libboost-dev
    - ( [ -d ./deps/eigen ] || git clone --depth 1 --branch 3.4.0 https://gitlab.com/libeigen/eigen.git ./deps/eigen)
    - ( [ -d ./deps/spectra ] || git clone --depth 1 --branch v0.9.0 https://github.com/yixuan/spectra.git ./deps/spectra)
    - ( [ -d ./deps/su3lib ] || git clone --depth 1 --branch cmake https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fasanowood.com/pjfasano/su3lib.git ./deps/su3lib)
    - cmake -DCMAKE_INSTALL_PREFIX=./deps -B./deps/build -S./deps/eigen && cmake --install ./deps/build && rm -rf ./deps/build
    - cmake -DCMAKE_INSTALL_PREFIX=./deps -B./deps/build -S./deps/spectra && cmake --install ./deps/build && rm -rf ./deps/build
    - cmake -DCMAKE_INSTALL_PREFIX=./deps -B./deps/build -S./deps/su3lib && cmake --build ./deps/build && cmake --install ./deps/build && rm -rf ./deps/build
  script:
    - cmake -DCMAKE_PREFIX_PATH=./deps -B build
  artifacts:
    paths:
      - build
      - deps
  cache:
    paths:
      - deps
      - /var/cache/apt

build:
  stage: build
  needs:
    - "configure"
  before_script:
    - apt update && apt -y install libgsl-dev libboost-dev
  script:
    - cmake --build build -j
  artifacts:
    paths:
      - build
  cache:
    paths:
      - build
      - "*.o"

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
